### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by aochsner**
in addition to static analysis, it also adds some style enforcement (more than the linter...there's probably some overlap).  I'm currently ignoring the maxlinelength warnings (set at 120 chars).  Everything else will fail the build (including javadoc on all public classes/objects/functions/etc... same rules apply to src, test, and test-e2e).  Lets kick the tires, argue about what we like and what is a bit much, and adjust from there

### CODE REVIEW

**Comment by mathomas** [comment]
In my experience, requiring JavaDoc on public stuff just makes people write useless documentation to get through the gate.  Or worse yet, rely on autogenerated fluff.

**Comment by aochsner** [comment]
I don't disagree w/ the sentiment... have similar experience too.  Unless you're writing a shared library/framework of sorts...  Hoping to discuss w/ @defpearlpilot when he's back next week.
Historically, I have liked writing a 1 line comment for each test stating, in text, what you think this test is testing.  After a number of refactors, you occasionally find a test isn't testing what it originally was supposed to be testing...

**Comment by aochsner** [comment]
So for now i'm going to leave the defaults (minus max lines... i dunno but that one seems enough to make an exception ;))

**Comment by aochsner** [comment]
BKIT-26

**Comment by defpearlpilot** [comment]
I'm generally not a fan of forcing comments unless this is an open source framework/library.  But I'm fine to leave it for now.  We can change the policy if we're . not getting value out of it.

**Comment by aochsner** [comment]
I also get frustrated forcing comments... so let's revisit next iteration then?

**Pull request merged**
